// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVWSIeLqKeuc0LQmlNRIsybGyEgLccD6c',
    appId: '1:897408699470:web:c51bf49a591f9f50d1871f',
    messagingSenderId: '897408699470',
    projectId: 'formscreen-c4e4f',
    authDomain: 'formscreen-c4e4f.firebaseapp.com',
    storageBucket: 'formscreen-c4e4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSk8hwXlyfG1CXYFDbgvhgzj8AENy87cI',
    appId: '1:897408699470:android:74406560589ce004d1871f',
    messagingSenderId: '897408699470',
    projectId: 'formscreen-c4e4f',
    storageBucket: 'formscreen-c4e4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8aeIv_yLaCKhAFGoIn8gefCMSNbP_Mto',
    appId: '1:897408699470:ios:12facf0987a24140d1871f',
    messagingSenderId: '897408699470',
    projectId: 'formscreen-c4e4f',
    storageBucket: 'formscreen-c4e4f.appspot.com',
    iosBundleId: 'com.example.task01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8aeIv_yLaCKhAFGoIn8gefCMSNbP_Mto',
    appId: '1:897408699470:ios:12facf0987a24140d1871f',
    messagingSenderId: '897408699470',
    projectId: 'formscreen-c4e4f',
    storageBucket: 'formscreen-c4e4f.appspot.com',
    iosBundleId: 'com.example.task01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVWSIeLqKeuc0LQmlNRIsybGyEgLccD6c',
    appId: '1:897408699470:web:02035e568a5e5096d1871f',
    messagingSenderId: '897408699470',
    projectId: 'formscreen-c4e4f',
    authDomain: 'formscreen-c4e4f.firebaseapp.com',
    storageBucket: 'formscreen-c4e4f.appspot.com',
  );
}
